### ISSUE TITLE
Issue when running project

### ISSUE THREAD

**Issue by innovatetom** [socioboard/Socioboard-4.0#101]
Hi

I am having an issue when running the project (Visual Studio 2015)

Please see the screenshot

<img width="358" alt="socioboard-error" src="https://user-images.githubusercontent.com/36082033/56150019-c58b6400-5fa5-11e9-9254-e50d6ad4443b.png">

Thanks in advance for any help

**Comment by Sathish-Globussoft** [comment]
Hello @innovatetom, Please pull the updated commit and try once.

**Comment by socioboard** [comment]
Hello!
Hope your issue is fixed.
As their is no further queries we are closing this issue.
