### ISSUE TITLE
Issue with socioboard-web-php

### ISSUE THREAD

**Issue by Jayanthbm** [socioboard/Socioboard-4.0#103]
I installed socioboard-web-php on centos following the instructions given in readme file but the application is not working I'm only getting socioboard index page

<img width="1397" alt="Screenshot 2019-07-18 at 12 03 15 PM" src="https://user-images.githubusercontent.com/14847969/61434703-4a469f00-a954-11e9-9a56-a3b5892962c8.png">
 
if I click sign in 404 error occurred
<img width="1284" alt="Screenshot 2019-07-18 at 12 05 45 PM" src="https://user-images.githubusercontent.com/14847969/61434774-84b03c00-a954-11e9-8709-3637693c1dc1.png">

**Comment by kuggaa** [comment]
This is not supported 

Non secure message

**Comment by Sathish-Globussoft** [comment]
Here you can find the PHP Configuration video. please have a look.

https://screencast-o-matic.com/watch/cqi0lNOxo3

**Comment by AishwaryaMurali** [comment]
The following url might help you to fix centos issues. please try once
https://stackoverflow.com/questions/54510527/my-laravel-routes-is-not-working-on-centos?answertab=active#tab-top

**Comment by hvsh** [comment]
I am having the same issue. My app url is set correctly. Laravel app is inside a sub directory with the structure http://localhost/socioboard/ homepage works fine, but clicking on any link leads to 404 as the url takes it to http://localhost/login instead of http://localhost/socioboard/login

**Comment by AishwaryaMurali** [comment]
Hello @hvsh ,
May I know what is the host url you have provided in .env file?

**Comment by hvsh** [comment]
APP_URL=http://127.0.0.1/socioboard

I don't see any host url option?
