### ISSUE TITLE
Install Docs for Socioboard-4.0 ???

### ISSUE THREAD

**Issue by kf202020** [socioboard/Socioboard-4.0#104]
Trying to install Socioboard-4.0 on my lamp stack server.
Impossible to even understand where to start. There are several guide on youtube about 3.0 ..... nothing about 4.0

The install doc is really really poor ( to be honest it's zero! ). Do you think can I get some help / further doc ?

Thanks

**Comment by hvsh** [comment]
+1

**Comment by Sathish-Globussoft** [comment]
You can find the configuration doc in following URLs

API Configuration:
https://github.com/socioboard/Socioboard-4.0/tree/master/socioboard-api

PHP Configuration: 
https://github.com/socioboard/Socioboard-4.0/tree/master/socioboard-web-php

We will make a video reference. will be sharing soon

**Comment by Sathish-Globussoft** [comment]
Here you can find the PHP Configuration video. please have a look

https://screencast-o-matic.com/watch/cqi0lNOxo3

**Comment by TechnologyClassroom** [comment]
youtube-dl works for screencast-o-matic if you do not want to use that site's JS.

`youtube-dl https://screencast-o-matic.com/watch/cqi0lNOxo3`

This socioboard mediawiki could really use some love: https://wiki.socioboard.com/index.php/Socioboard_Installation_Wiki  That should point directly to the three links listed here.  There is no public editing allowed on that mediawiki.

**Comment by BloodyIron** [comment]
Yeah it would be nice to have a single install doc to reference that is clearly spelled out front to back. It's rather unclear on every aspect to take into consideration.

**Comment by TechnologyClassroom** [comment]
Nothing seemed to change.  Why was this ticket closed?

**Comment by BloodyIron** [comment]
Yeah, why was this closed?

**Comment by AishwaryaMurali** [comment]
We have provided document/video for api and web.
Please refer :

1. API Configuration :

- Document => https://github.com/socioboard/Socioboard-4.0/tree/master/socioboard-api

- Video => 1st -- http://somup.com/cqjIXAeroO
                  2nd -- http://somup.com/cqjIlTerDW

 PHP Configuration
- Document => https://github.com/socioboard/Socioboard-4.0/tree/master/socioboard-web-php

-Video => https://screencast-o-matic.com/watch/cqi0lNOxo3


You can reopen anytime

**Comment by BloodyIron** [comment]
There are steps that are missing in those docs, I've been going through them. I recommend you try following them front to back with a fresh Ubuntu 18.04 LTS install, and you'll see steps missing.

**Comment by TechnologyClassroom** [comment]
We cannot reopen an issue.

Are these screencasts linked from anywhere else?  I will watch them later.  The first one from this thread is incomplete.  I agree with @BloodyIron that the best way to build instructions is from starting with a bare-bones fresh install and building up.  Starting with a development machine usually results in missing dependencies.

The README.md should include complete installation instructions.

The mediawiki is out of date, needs to allow users to contribute, or needs to get ported to github.

youtube-dl works for screencast-o-matic if you do not want to use that site's JS.  Here are the download links for the new videos:

```
youtube-dl https://screencast-o-matic.com/watch/cqjIXkOSGD
youtube-dl https://screencast-o-matic.com/watch/cqjIlUOSJ8
```

**Comment by BloodyIron** [comment]
I've actually been trying to do it from front to back myself, hoping to build an article, but I'm sure it would be generally appreciated if the original/official source had every step outlined. And in my testing thus-far, there are steps missing.

That being said, for me, I do appreciate the info that is already there, without it I would be a fish out of water.

From my perspective, I'm more trying to say that there is room for improvement, and as it is right now, I would argue the steps are incomplete. While I myself, a Sr Linux Admin/Architect, can fill in the gaps, others may not know how to do that.

**Comment by TechnologyClassroom** [comment]
@BloodyIron Did you succeed?  Pasting a list of commands in this thread or submitting a PR to the README.md would be impactful.

**Comment by BloodyIron** [comment]
> @BloodyIron Did you succeed? Pasting a list of commands in this thread or submitting a PR to the README.md would be impactful.

I have not completed my work, and unfortunately was set back due to a hard-lock before I saved a bunch of my notes. So, "not yet" :P

**Comment by TornMarketing** [comment]
$50 bucks for someone to get a working demo up on my server. :)
