### ISSUE TITLE
Registration and login issue in localhost

### ISSUE THREAD

**Issue by rajithagarapati** [socioboard/Socioboard-4.0#110]
I am using socioboard 3.0.
 I am getting the failure error when i try to register user. I am getting the following error
{"System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.NullReferenceException: Object reference not set to an instance of an object.\n   at Api.Socioboard.Helper.SessionFactory.GetNewSession() in D:\\Projects\\socioboard-core-master\\SocioBoard\\SocioboardAPI\\Helper\\SessionFactory.cs:line 68\n   at Api.Socioboard.Model.UserRepository.getUserInfoByEmail(String emailId) in D:\\Projects\\socioboard-core-master\\SocioBoard\\SocioboardAPI\\Model\\UserRepository.cs:line 322\n   at Api.Socioboard.Services.User.getUserInfoByEmail(String userEmail) in D:\\Projects\\socioboard-core-master\\SocioBoard\\SocioboardAPI\\Services\\User.asmx.cs:line 544\n   --- End of inner exception stack trace ---"}

Kindly look into issue and help me as fast as possible

**Comment by rajithagarapati** [comment]
hi, today i am getting this issue.  It seems like your connectivity to the internet is impaired and no connection could be made because the target machine actively refused it 127.0.0.1:6361

**Comment by somnathglobussoft** [comment]
Hello rajithagarapati,
most probably the issue is 6361 port is not free in your system. you can change the port but you have to do the same changes in dashboard project.

**Comment by rajithagarapati** [comment]
No, port 6361 is free. i am getting error while inserting record in groups table

**Comment by rajithagarapati** [comment]
its working.. in nhibernate we have to provide backticks(``) for table
