### ISSUE TITLE
Unable to get instagram access token

### ISSUE THREAD

**Issue by rajithagarapati** [socioboard/Socioboard-4.0#111]
I am unable to get access token for instagram likes and public content scope.. will you provide any sample accesstoken? Without this accesstoken i cannot see any public content or hashtag results on my website.. Will you please look into this issue as soon as possible?

**Comment by somnathglobussoft** [comment]
Hello rajithagarapati,
we are using Instagram non-business account for socioboard 3.0. please follow this doc (https://www.instagram.com/developer/endpoints/) for more information regarding the endpoints .
