### ISSUE TITLE
Migrate tables doesn't work !

### ISSUE THREAD

**Issue by kaayso** [socioboard/Socioboard-4.0#113]
Hello,

I'm trying to  initialize the Mysql. When I run this command `socioboard-api/library/sequelize-cli> ../node_modules/.bin/sequelize db:migrate` it doesn't work and seems that path doesn't exists... 

Please, how can I fix this? thanks

```
PHP 7.3.9
OS: Windows 10
```

**Comment by sureshbabu1995** [comment]
please go inside the folder  (sequelize-cli), open the command prompt by searching "cmd" in search bar , you'll see you're in sequelize-cli folder then execute > sequelize db:migrate  (or)  > npx sequelize db:migrate Ref : http://prntscr.com/p89dl5

if sequelize-cli is installed globally sequelize db:migrate will work, else go with another command

**Comment by AishwaryaMurali** [comment]
Hi @kaayso ,
Since there is no further queries we are closing this issue.
Feel free to open it, if you face this issue in the future
