### ISSUE TITLE
Issues when trying to install Socioboard-api

### ISSUE THREAD

**Issue by Asim187** [socioboard/Socioboard-4.0#114]
poor documentation on API installation getting the error all over 

`D:\wamp\www\social\user>npm install
npm WARN user@1.0.0 No description
npm WARN user@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 877396 packages in 46.139s
found 0 vulnerabilities`

and 

D:\wamp\www\social\library\sequelize-cli> ../node_modules/.bin/sequelize db:migrate
'..' is not recognized as an internal or external command,
operable program or batch file.

**Comment by vikashglb** [comment]
By the above error log, it shows, you are using relative path. Try the same command inside with

>> cd node_modules/.bin
>> sequelize db:migrate <path_to_the_migration_file>
