### ISSUE TITLE
(node:1220) [SEQUELIZE0004] DeprecationWarning:

### ISSUE THREAD

**Issue by Asim187** [socioboard/Socioboard-4.0#117]
when I am trying to run nodemon app.js socioboard-api/user I am getting the following error

`(node:1220) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.`

I just solved this by removing `"operatorsAliases": false,` from https://github.com/socioboard/Socioboard-4.0/blob/master/socioboard-api/library/sequelize-cli/config/config.json

**_suggested by Mr. Hamza Mohamed on_** https://stackoverflow.com/questions/58220980/node-js-node12276-sequelize0004-deprecationwarning
  
does it safe to remove `"operatorsAliases": false,`  from config.json?

Thank you.

**Comment by AishwaryaMurali** [comment]
> when I am trying to run nodemon app.js socioboard-api/user I am getting the following error
> 
> `(node:1220) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.`
> 
> I just solved this by removing `"operatorsAliases": false,` from https://github.com/socioboard/Socioboard-4.0/blob/master/socioboard-api/library/sequelize-cli/config/config.json
> 
> **_suggested by Mr. Hamza Mohamed on_** https://stackoverflow.com/questions/58220980/node-js-node12276-sequelize0004-deprecationwarning
> 
> does it safe to remove `"operatorsAliases": false,` from config.json?
> 
> Thank you.

Hello @Asim187 ,
Yes you can remove because in the updated sequelize package it has been removed.
Thank you.
