### ISSUE TITLE
Page redirects 404 after clicking on dashboard url socioboard-web-php/dashboard

### ISSUE THREAD

**Issue by Asim187** [socioboard/Socioboard-4.0#118]
Hello
when I am clicking on SocioBoard logo I think it should have to point dashboard URL i.e socioboard-web-PHP/dashboard but it redirects to page 404 error
I installed it using  https://github.com/socioboard/Socioboard-4.0/tree/master/socioboard-web-php.
do am I missing something?

and there is nothing about database installation in the [readme.md file](https://github.com/socioboard/Socioboard-4.0/blob/master/socioboard-web-php/README.md).
doesn't Larvel part requires a database.
I hope it will get updated soon.

**Comment by vikashglb** [comment]
> 
> 
> Hello
> when I am clicking on SocioBoard logo I think it should have to point dashboard URL i.e socioboard-web-PHP/dashboard but it redirects to page 404 error
> I installed it using https://github.com/socioboard/Socioboard-4.0/tree/master/socioboard-web-php.
> do am I missing something?
> 
> and there is nothing about database installation in the [readme.md file](https://github.com/socioboard/Socioboard-4.0/blob/master/socioboard-web-php/README.md).
> doesn't Larvel part requires a database.
> I hope it will get updated soon.

We will update our readme.md soon for more detailed explanation.

Thanks for pointing "Socioboard Logo" redirection issue. Can you elaborate where have you found this?

And as far as database is concerned , we are not using any database in Laravel part. Every database operation id from NodeJS Part of the project.

**Comment by Asim187** [comment]
after installing the Laraval part. In the header logo, it redirects to 404 page

**Comment by vikashglb** [comment]
I will check with the developers and get it rectified.

**Comment by AishwaryaMurali** [comment]
> I will check with the developers and get it rectified.

Hello,
Is it before login or after login?

**Comment by AishwaryaMurali** [comment]
Can you provide me screenshot?

**Comment by Asim187** [comment]
it is before login
when I am trying to register as a new user I am getting an error for more please refer this #120 

here is a screenshot of 404error when I try to access the dashboard
https://paste.pics/02d947ca1054f8ce6ffd16ed23d4a75d

if it works on login it should be point to the dashboard after login only otherwise it should point to the homepage of page

**Comment by AishwaryaMurali** [comment]
Its working i have attached a video please refer..
Check if everything is configured in your .env file

https://screencast-o-matic.com/watch/cq6Qi4u0Qk
