### ISSUE TITLE
Validation error: Phone code should have valid characters. in signup

### ISSUE THREAD

**Issue by Asim187** [socioboard/Socioboard-4.0#120]
when I signup for a new user, I am getting an error message

> Validation error: Phone code should have valid characters.

where there is no such field in the form

Request: If there is a demo data then it should be more usefull. such as defaul user, password and all

**Comment by AishwaryaMurali** [comment]
Its working i have attached a video please refer..
Check if everything is configured in your .env file

https://screencast-o-matic.com/watch/cq6Qi4u0Qk
