### ISSUE TITLE
update demo data

### ISSUE THREAD

**Issue by Asim187** [socioboard/Socioboard-4.0#122]
can you guys please update demonstrative user details MySQL database 
please refer this issue on StackOverflow
https://stackoverflow.com/questions/58360838/email-verification-not-working-in-socioboard-4-0

**Comment by praveenchauhan2169** [comment]
pull the current code and you can seed the demo users from this file 
20190507065043-initialize_dummy_users.js, which is present here :
https://github.com/socioboard/Socioboard-4.0/tree/master/socioboard-api/library/sequelize-cli/seeders

**Comment by Asim187** [comment]
getting an error when I initialize seed
Error : SequelizeDatabaseError: Incorrect datetime value: '2019-11-02T08:53:43Z' for column 'email_token_expire' at row 1

**Comment by sureshbabu1995** [comment]
> getting an error when I seed
> `Error : SequelizeDatabaseError: Incorrect datetime value: '2019-11-02T08:53:43Z' for column 'email_token_expire' at row 1`

**For your purpose** I just cloned the fresh code of this and I Installed all packages in library `(npm i)` then I setup DB config in `config.json` file in 

> Socioboard-4.0-master\socioboard-api\library\sequelize-cli\config

Then executed migration command and then I did **seeding of particular dummy_users** and **undo all** and **seed all** , **all commands of seed is working properly to me ** 

> email_expire_token allows null also

Please check once and update the Issue
