### ISSUE TITLE
VPS Requeriments

### ISSUE THREAD

**Issue by javiereaw** [socioboard/Socioboard-4.0#124]
I want to install Socioboard in a VPS. What is the best environment for this software: Debian, Ubuntu, ram memory...

Thank you

**Comment by sureshbabu1995** [comment]
**OS**: 

> Debian, Ubuntu, centOs [ recommended ]

**RAM** : 

> minimum 4 GB

**Storage** : 

> initially 30-50 GB [ varies ]
