### ISSUE TITLE
sequelize db:migrate Issue

### ISSUE THREAD

**Issue by deso127** [socioboard/Socioboard-4.0#131]
After putting in the mysql info and running the 'sequelize db:migrate' command in the sequelize-cli folder, there's an error that comes up. What needs to be done to fix this?

`Sequelize CLI [Node: 10.15.2, CLI: 5.5.1, ORM: 5.10.0]

ERROR: Error reading "config/config.json". Error: SyntaxError: /home/s/Socioboard-4.0-master/socioboard-api/library/sequelize-cli/config/config.json: Unexpected token r in JSON at position 64`

**Comment by vikashglb** [comment]
Its look like, you have not configured the config.json file properly.

Check your config.json file [ref](https://github.com/socioboard/Socioboard-4.0/blob/master/socioboard-api/library/sequelize-cli/config/config.json)
