### ISSUE TITLE
Api Callback and addsocialprofile

### ISSUE THREAD

**Issue by deso127** [socioboard/Socioboard-4.0#132]
How are you supposed to setup the api callback urls and the addsocialprofile urls in the default and development.json files? I'm setting all of this up on an external server with a domain name.

**Comment by sureshbabu1995** [comment]
> How are you supposed to setup the api callback urls and the addsocialprofile urls in the default and development.json files? I'm setting all of this up on an external server with a domain name.

Thanks For the Interest of knowing the Usage, We are using

>  **Config** Package

 from **

> NPM

** 

Refer: [https://www.npmjs.com/package/config](about config package) - **Study fully** in-order to understand, how it is working.

**Comment by pehelle** [comment]
I want to know how to get white listed official facebook API ID . facebook blocked my account when i posted bucks message via API

**Comment by sureshbabu1995** [comment]
Sorry for the violation issues (of Facebook terms&conditions), we can't help in that, But we can just guide you to create a developer account [https://developers.facebook.com/docs/app-ads/app-setup/#create](url) and setting up  new APP for usage [https://developers.facebook.com/docs/apps/](url)

> Follow these steps **to get APP ID**

or else contact the Facebook support [https://www.facebook.com/help/community](url) to get it UN-blocked.

**Comment by sureshbabu1995** [comment]
> I want to know how to get white listed official facebook API ID . facebook blocked my account when i posted bucks message via API

Sorry for the violation issues (of Facebook terms&conditions), we can't help in that, But we can just guide you to create a developer account [https://developers.facebook.com/docs/app-ads/app-setup/#create](url) and setting up  new APP for usage [https://developers.facebook.com/docs/apps/](url)

> Follow these steps **to get APP ID**

or else contact the Facebook support [https://www.facebook.com/help/community](url) to get it UN-blocked.

**Comment by Quin452** [comment]
So I guess there is still no answer in "how to add <host_name>/[whatever]-callback".

There are no instructions in this, whatsoever.  Just "add them".

**Comment by sureshbabu1995** [comment]
> So I guess there is still no answer in "how to add <host_name>/[whatever]-callback".
> 
> There are no instructions in this, whatsoever. Just "add them".

**host_name**  Means Your application Domain

**Comment by Quin452** [comment]
> > So I guess there is still no answer in "how to add <host_name>/[whatever]-callback".
> > There are no instructions in this, whatsoever. Just "add them".
> 
> **host_name** Means, Your application Domain.
> **whatever** Means, the application name " like facebook for Facebook application ".
> 
> Finally it will be like "
> 
> > [www.socioboard.com/facebook-callback](http://www.socioboard.com/facebook-callback)
> 
> "

Yes, but where are they added?  What file?

The instructions are not clear and out dated, as they do not match up with what is in the repo, let alone the repo themselves not aligning up (there is the Master branch, which seems to be an updated version of the 4.0 branch).

**Comment by sureshbabu1995** [comment]
> > > So I guess there is still no answer in "how to add <host_name>/[whatever]-callback".
> > > There are no instructions in this, whatsoever. Just "add them".
> > 
> > 
> > **host_name** Means, Your application Domain.
> > **whatever** Means, the application name " like facebook for Facebook application ".
> > Finally it will be like "
> > > [www.socioboard.com/facebook-callback](http://www.socioboard.com/facebook-callback)
> > 
> > 
> > "
> 
> Yes, but where are they added? What file?
> 
> The instructions are not clear and out dated, as they do not match up with what is in the repo, let alone the repo themselves not aligning up (there is the Master branch, which seems to be an updated version of the 4.0 branch).

You can keep those in `Socioboard-4.0/socioboard-api/{micro-controller}/config/development.json`

> Micro-controllers are the 4 folders ( user, feeds, publish, notifications )

**Thing is We already kept the URL's as domain of localhost:300[1,2,3,4]**

If you want, You can update them and **You should provide the Keys and Id's** 

[http://prntscr.com/qq1wn8](url)

**Comment by Quin452** [comment]
Okay, say I want to install this on Ubuntu 18.04, as a subdomain (socio.domain.com)
The host file is already in place, pointing to /var/www/html/socio

What is needed to be done?

**Comment by TechnologyClassroom** [comment]
@Quin452 Without sharing your commands, not much can be done to help troubleshoot.  We have yet to see a complete set of instructions.

**Comment by sureshbabu1995** [comment]
> Okay, say I want to install this on Ubuntu 18.04, as a subdomain (socio.domain.com)
> The host file is already in place, pointing to /var/www/html/socio
> 
> What is needed to be done?

**Irrespective of OS**, This application asks for 3 Sections,

**Comment by sureshbabu1995** [comment]
> Okay, say I want to install this on Ubuntu 18.04, as a subdomain (socio.domain.com)
> The host file is already in place, pointing to /var/www/html/socio
> 
> What is needed to be done?

**Irrespective of OS,** This application asks for 3 Sections,
1. PHP and Node installations, Base setup videos ( "http://somup.com/cqjIXAeroO" & "http://somup.com/cqjIlTerDW" ), These are base things you can google and do it in any OS.
2. Database setups ( Sql & Mongoose ).
3. Social Networks Config

Mostly you should know how to execute commands for running node properly, and that instructions are given in the Doc.

The installation Doc is based on Linux, Videos are based on Windows system, Overall Process is same in any OS.
