### ISSUE TITLE
I downloaded php version   Socioboard-4.0  . the vendor folder is missing here 

### ISSUE THREAD

**Issue by pehelle** [socioboard/Socioboard-4.0#133]
I downloaded php version   Socioboard-4.0  . the vendor folder is missing here .
and i want to know how to get white listed official facebook API ID . facebook blocked my account when i posted bucks message via API

**Comment by AishwaryaMurali** [comment]
For the vendor folder please update the composer.
`$ composer update`

**Comment by sureshbabu1995** [comment]
> I downloaded php version Socioboard-4.0 . the vendor folder is missing here .
> and i want to know how to get white listed official facebook API ID . facebook blocked my account when i posted bucks message via API

Sorry for the violation issues (of Facebook terms&conditions), we can't help in that, But we can just guide you to create a developer account [https://developers.facebook.com/docs/app-ads/app-setup/#create](url) and setting up  new APP for usage [https://developers.facebook.com/docs/apps/](url)

> Follow these steps **to get APP ID**

or else contact the Facebook support [https://www.facebook.com/help/community](url) to get it UN-blocked 
.

**Comment by pehelle** [comment]
I downloaded php version Socioboard-4.0 . the vendor folder is missing here .

**Comment by sureshbabu1995** [comment]
> I downloaded php version Socioboard-4.0 . the vendor folder is missing here .

For the **vendor** folder please update the composer.
`$ composer update`
