### ISSUE TITLE
nodemon not listening to service

### ISSUE THREAD

**Issue by JonathanDeBelg** [socioboard/Socioboard-4.0#142]
Hi,

I am installing the socioboard-api part. Now i have setup the mongo creds, and socials media creds in the development.json file. While running; 'nodemon app.js' in the /user service, i get the following result; 
![image](https://user-images.githubusercontent.com/36629491/76025502-5efc9500-5f2d-11ea-98e0-a0921b5b2dba.png)
As you can see the service has started, but nodemon is not yet listening to the service via a (web)address. Is there any fix for this? I pressume the mongo creds are correct, because when looking to the collections in the mongodb i see the following;
![image](https://user-images.githubusercontent.com/36629491/76025614-9bc88c00-5f2d-11ea-8c70-2b60da1f1e69.png)
Also i get no error log in the /public/logs/user... folder.

Thanks in advance for helping out!

**Comment by sureshbabu1995** [comment]
Hi, @JonathanDeBelg 

Sorry for the inconvenience,
That document of config need to get update for sequlelize 5.0 + 
Till that can you please remove ` "operatorsAliases": false,` this line from the config file `socioboard-api/library/sequelize-cli/config/config.json`  in all objects or only in your respective environment object.

This line user to work till sequelize 5 but as you installing fresh the sequelize version you'll get is current version which is of `5.21.5` so it's not accepting it, 

Soon we'll update the file.

Thank You.

**Comment by JonathanDeBelg** [comment]
Hi, thanks for the help!
I deleted the line from the environment object. It now looks as following;
`"username": "root",
    "password": "",
    "database": "socioboard-api",
    "host": "127.0.0.1",
    "port": 3306,
    "dialect": "mysql",
    "pool": {
      "max": 100,
      "min": 0,
      "acquire": 1000000,
      "idle": 200000
    },`
Still when running nodemon app.js i dont get further but `[nodemon] starting 'node app.js'`;
![image](https://user-images.githubusercontent.com/36629491/76062104-48822800-5f85-11ea-9027-7f88a9e92794.png)

Thanks in advance!

**Comment by JonathanDeBelg** [comment]
> Hi, @JonathanDeBelg
> 
> Sorry for the inconvenience,
> That document of config need to get update for sequlelize 5.0 +
> Till that can you please remove ` "operatorsAliases": false,` this line from the config file `socioboard-api/library/sequelize-cli/config/config.json` in all objects or only in your respective environment object.
> 
> This line user to work till sequelize 5 but as you installing fresh the sequelize version you'll get is current version which is of `5.21.5` so it's not accepting it,
> 
> Soon we'll update the file.
> 
> Thank You.

Hi, thanks for the help @sureshbabu1995!

So my sequelize-cli version is 5.5.1.
I deleted the line from the environment object. It now looks as following;
`"username": "root",
    "password": "",
    "database": "socioboard-api",
    "host": "127.0.0.1",
    "port": 3306,
    "dialect": "mysql",
    "pool": {
      "max": 100,
      "min": 0,
      "acquire": 1000000,
      "idle": 200000
    },`
Still when running nodemon app.js i dont get further but `[nodemon] starting 'node app.js'`;
![image](https://user-images.githubusercontent.com/36629491/76062104-48822800-5f85-11ea-9027-7f88a9e92794.png)

Thanks in advance!

**Comment by JonathanDeBelg** [comment]
@sureshbabu1995 do you maybe have a answer for me?

**Comment by sureshbabu1995** [comment]
You can check the errors in the log files `user\public\logs\user20200306.log` file format is like serviceName+Date.log check the file

if you're running any other services then you can check in that service path  `{service}\public\logs\user20200306.log`

**Comment by JonathanDeBelg** [comment]
Thanks for your help @sureshbabu1995 !

While looking into the logs, i came accross the next error;
`{ message: 'Cron setup intialized for monthly user stats...',
  level: 'info',
  timestamp: '2020-03-06T13:21:46.709Z' }
{ message: 'Mongo Database has been connected.',
  level: 'info',
  timestamp: '2020-03-06T13:21:48.846Z' }
{ message: 'Sequelize Database has been connected.',
  level: 'info',
  timestamp: '2020-03-06T13:21:49.112Z' }
**{ message: 'Configuration property "payment.base_path" is not defined',
  level: 'error',
  timestamp: '2020-03-06T13:21:49.244Z' }**
`

Do i need to change something in the development.json file, like adding the base_path? If so; where does my base_path need to lead to?

Thanks in advance!

**Comment by sureshbabu1995** [comment]
Hi, @JonathanDeBelg ,

That is for making folders to download media and some other contents if you requested ( like receipts of payment )
`
![image](https://user-images.githubusercontent.com/55544386/76136873-68d0e600-605c-11ea-9151-ff2982ee89b1.png)
`

In user services config development.json

**Comment by JonathanDeBelg** [comment]
Hi @sureshbabu1995 ,

After adding the code it works! Thanks a lot for the time taken. Just a question; why aren't the `base_path, payment_path and template` not added in the development.json? Won't this be a problem for other installation?

Thankyou!

**Comment by sureshbabu1995** [comment]
Hi, @JonathanDeBelg 

That's a great question, 
but if people wanted to keep other names they can as it is a constant path 

Like, we kept media some people can keep storage or some other name , we don't want to restrict them by keeping the same constant name..

If this is scenario in the next updates we'll keep in detail details of each variable and an example for that.

Hope you enjoy the features of this application.

**Comment by danieladi050** [comment]
can you explain in more detail how and where you add the "base_path" etc ? @JonathanDeBelg @sureshbabu1995
