### ISSUE TITLE
While executing localhost:3000 i am getting access forbidden error

### ISSUE THREAD

**Issue by yogesh23021995** [socioboard/Socioboard-4.0#151]
While executing localhost:3000 i am getting access forbidden error

**Comment by sureshbabu1995** [comment]
Hi, @yogesh23021995,

Can you please elaborate the question, in which scenario you got this problem and where you got it

**Comment by yogesh23021995** [comment]
HI @sureshbabu1995 ,
I was able to resolve forbidden access issue, it however I am not able to hit api successfully,
Error Message : "code":401,"status":"failed","message":"Accesstoken is missing or invalid!"}
Attached screenshot below :
![image](https://user-images.githubusercontent.com/50060627/78420671-c877dc80-766e-11ea-85b5-f5a087b32f7d.png)

**Comment by sureshbabu1995** [comment]
Hi, @yogesh23021995 

If you don't mind who gave that URL ??

**Use** [http://localhost:3000/explorer](URL) it will open ( swagger ) a page where you can see all the API's

if any API is having locked symbol means you can't access without Access Token.

**Comment by yogesh23021995** [comment]
So, I won't able to call APIs individually using postman,

If you don't mind can we have a quick screen share call

**Comment by sureshbabu1995** [comment]
**We can use but you should know which API needs Access Token and how to use it,** 

No problem with screen share call but I'll be available from 10:30 am to 7:00 pm (IST ).

**Comment by yogesh23021995** [comment]
Yes ,I will send a screenshare link shortly

**Comment by yogesh23021995** [comment]
To join the video meeting, click this link: https://meet.google.com/mbh-vxkb-ski
Otherwise, to join by phone, dial +1 260-305-0061 and enter this PIN: 746 263 158#
To view more phone numbers, click this link: https://tel.meet/mbh-vxkb-ski?hs=5

**Comment by yogesh23021995** [comment]
Let me know when can we start my Direct calling number  9096367225
