### ISSUE TITLE
cannot parse config file

### ISSUE THREAD

**Issue by danieladi050** [socioboard/Socioboard-4.0#154]
it only happen in the microservice of notification. the rest microservice doesnt have any problem. the error directing to default and config not development. im pretty sure i have config my mongodb rightfully, any idea ? @socioboard @swetasb 
btw this is my log
{ error:
Error: Cannot parse config file: 'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\config\default.json': SyntaxError: Unexpected token } in JSON at position 1849
at Config.util.parseFile (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:844:11)
at C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:600:28
at Array.forEach ()
at C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:596:14
at Array.forEach ()
at Config.util.loadFileConfigs (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:595:13)
at new Config (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:136:27)
at Object. (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:1649:31)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10),
level: 'error',
message:
'uncaughtException: Cannot parse config file: 'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\config\default.json': SyntaxError: Unexpected token } in JSON at position 1849\nError: Cannot parse config file: 'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\config\default.json': SyntaxError: Unexpected token } in JSON at position 1849\n at Config.util.parseFile (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:844:11)\n at C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:600:28\n at Array.forEach ()\n at C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:596:14\n at Array.forEach ()\n at Config.util.loadFileConfigs (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:595:13)\n at new Config (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:136:27)\n at Object. (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:1649:31)\n at Module._compile (internal/modules/cjs/loader.js:776:30)\n at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)',
stack:
'Error: Cannot parse config file: 'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\config\default.json': SyntaxError: Unexpected token } in JSON at position 1849\n at Config.util.parseFile (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:844:11)\n at C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:600:28\n at Array.forEach ()\n at C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:596:14\n at Array.forEach ()\n at Config.util.loadFileConfigs (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:595:13)\n at new Config (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:136:27)\n at Object. (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js:1649:31)\n at Module._compile (internal/modules/cjs/loader.js:776:30)\n at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)',
exception: true,
date: 'Sat Apr 04 2020 01:16:54 GMT+0700 (Indochina Time)',
process:
{ pid: 4424,
uid: null,
gid: null,
cwd:
'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification',
execPath: 'C:\Program Files\nodejs\node.exe',
version: 'v10.16.0',
argv:
[ 'C:\Program Files\nodejs\node.exe',
'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\app.js' ],
memoryUsage:
{ rss: 38584320,
heapTotal: 23838720,
heapUsed: 12203912,
external: 84472 } },
os: { loadavg: [ 0, 0, 0 ], uptime: 52439 },
trace:
[ { column: 11,
file:
'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js',
function: 'Config.util.parseFile',
line: 844,
method: 'parseFile',
native: false },
{ column: 28,
file:
'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js',
function: null,
line: 600,
method: null,
native: false },
{ column: null,
file: null,
function: 'Array.forEach',
line: null,
method: 'forEach',
native: false },
{ column: 14,
file:
'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js',
function: null,
line: 596,
method: null,
native: false },
{ column: null,
file: null,
function: 'Array.forEach',
line: null,
method: 'forEach',
native: false },
{ column: 13,
file:
'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js',
function: 'Config.util.loadFileConfigs',
line: 595,
method: 'loadFileConfigs',
native: false },
{ column: 27,
file:
'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js',
function: 'new Config',
line: 136,
method: null,
native: false },
{ column: 31,
file:
'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\node_modules\config\lib\config.js',
function: null,
line: 1649,
method: null,
native: false },
{ column: 30,
file: 'internal/modules/cjs/loader.js',
function: 'Module._compile',
line: 776,
method: '_compile',
native: false },
{ column: 10,
file: 'internal/modules/cjs/loader.js',
function: 'Module._extensions..js',
line: 787,
method: '.js',
native: false } ],
timestamp: '2020-04-03T18:16:54.616Z' }

**Comment by sureshbabu1995** [comment]
This is Json Validation error , if you want, you can just open any online json parser and test that the file data is proper or not..

**Comment by yogesh23021995** [comment]
> This is JSON Validation error, if you want, you can just open any online JSON parser and test that the file data is proper or not.
> 
> As this line says
> 
> > Error: Cannot parse config file: 'C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\notification\config\default.json': SyntaxError: Unexpected token } in JSON at position 1849
> 
> error in default.json file so please go and check that file is proper or not with online soon parser..

Yes there }, in the notification/config.js replace with }.

**Comment by danieladi050** [comment]
oh yeah, i dont work with json file too much so that confused me. thank you very much. for anyone who got this error, your default.json file ( or error file ) to this link https://jsonformatter.org/json-parser or other online json parser. it immediately show you the error. thanks for you time and care @sureshbabu1995 @yogesh23021995
