### ISSUE TITLE
Login page buttons error and can't access dashboard

### ISSUE THREAD

**Issue by kimbo9674** [socioboard/Socioboard-4.0#161]
I have followed the given documentation and have all 4 of the API services running on nodemon and can view them in swagger. The MongoDB and SQL databases are successfully connected too. 

When using php artisan serve the login page is hosted but has no functionality.

![2020-04-16](https://user-images.githubusercontent.com/63161834/79467599-d8d87180-7ff5-11ea-9126-1f95c275cad3.png)

When clicking login it just throws an error and doesn't progress to the dashboard.

Is there a known reason for this?

**Comment by sureshbabu1995** [comment]
Hi, @kimbo9674 

This login buttons Fully Depends on the Node code is that is running perfectly then these all buttons will work properly

**Comment by kimbo9674** [comment]
Hi @sureshbabu1995,

I went back through node setup and reran the steps and checked that the .env file contained the API URLs.

I've also had a look at the node setup through swagger. The user api 'login' when executed comes up with the error "TypeError: NetworkError when attempting to fetch resource.". I've tried inspecting the network error on firefox using the developer network tools and come across "Referrer Policy:strict-origin-when-cross-origin". 

Unsure if this is the solution, I'm guessing I still don't have something set up correctly with node?

**Comment by sureshbabu1995** [comment]
Hi, @kimbo9674 

This is of 2 conditions

1. Check the node setup and try using swagger to do all the things like register and login 

and then check in the PHP side , if still a problem try tocheck the env of PHP API_url 

and if still have problem

**Comment by kimbo9674** [comment]
Hi @sureshbabu1995 ,

How would you like me to share my screen?
Thanks for your help.

**Comment by sureshbabu1995** [comment]
Hi, @kimbo9674 

We can use **TeamViewer** or **anydesk** To share the screen

**Comment by kimbo9674** [comment]
Hi @sureshbabu1995,

TeamViewer would be preferred, how do I share the ID and password with you?

**Comment by sureshbabu1995** [comment]
Hi, @kimbo9674 

sureshbabu@globussoft.in is my email you can send here ..

**Comment by rishabh001995** [comment]
Hello, @sureshbabu1995 i am having the similar problem as @kimbo9674 mentioned it. Node API is working fine i checked it with swagger but the PHP front-end is not working at all. I can't login or signup or anything in the front end. Any thing clicked leads to a error "Something went wrong". The log file shows 2 error 

local.INFO: Sign up Exception 201 => cURL error 3:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
local.ERROR: Undefined variable: result {"exception":"[object] (ErrorException(code: 0): Undefined variable: result at C:\\xampp\\htdocs\\so\\app\\Modules\\User\\Controllers\\UserController.php:132)

Any help is appreciated.
Thank you
