### ISSUE TITLE
linux installation script ?

### ISSUE THREAD

**Issue by apcloic** [socioboard/Socioboard-4.0#2]
Hi,
Socioboard team has announced that Socioboard 3.0 will come with a linux install script in the following thread :
 https://github.com/socioboard/socioboard-core/issues/10

AFAIK, version 3.0 is out for some time, do you still plan to release this script or not ?

Regards,

**Comment by alexanderahlsen** [comment]
I have the same question!

**Comment by alexanderahlsen** [comment]
Hello? @socioboard

**Comment by socioboard** [comment]
Yes the linux install is in test stages, there are lot of .net dependencies which are .net core is not supporting in linux natively as of now. We are working on porting them. It would take some time. A lot of our work is directly related to Microsoft's ETA on porting .NET Core to linux completely.

**Comment by alexanderahlsen** [comment]
Ok, from what I understood you were done with it. So no ETA on that? I'm in need of the Linux version :)

**Comment by glunardi** [comment]
Version  1.1.1 of .NET Core (and the rest) was release in March closing quite a few gaps.  

Would be happy to help test the GNU/Linux installation and report back.  Could you please share the instructions (in whatever state they are in) even if they result in build/install failures still?

**Comment by woakes070048** [comment]
How is this coming for the Linux install?

**Comment by xSeekTruthx** [comment]
@woakes070048 Sounds like it's not :/

**Comment by RajibBiswas** [comment]
I guess I am too old to fight with windows environment. Eagerly waiting to test it in Linux.

**Comment by chrisp1001** [comment]
The .NET Core seems to be already ported to Linux: https://www.microsoft.com/net/download/linux

+1 for a solution

**Comment by socioboard** [comment]
The core team is busy adding new features based on user feedback on the core product and hence we are little out of bandwidth. In the coming months, we plan to migrate the core architecture to micro-services based architecture which each micro-service running in a docker based container. But this will take some months of work. If any of you want to participate in the project you can mail your interest to sumit[at]socioboard.com and we can take you up in the core team.

Sumit

**Comment by layerlre** [comment]
+1

**Comment by obusher** [comment]
+1

We love socioboard and linux!

**Comment by proffalken** [comment]
Hi, I'm also interested in this, even if the installation script doesn't exist yet, is there a document on how to install/get it up and running?

**Comment by RCheesley** [comment]
Ditto, there's an issue with some instructions for Arch see #72 for anyone coming into this issue directly!

**Comment by obusher** [comment]
It would be nice if you could push the scripts, even if they are not working and/or are not tested.
(@socioboard )

**Comment by motermouth15** [comment]
Just out of curiosity, is there an update with this project porting over to Linux at all? 

I've been surfing the web all morning trying to find literally any materials on how to get socioboard up and running on a linux environment. Thanks!

**Comment by pietrondo** [comment]
same..
+linux

**Comment by BloodyIron** [comment]
yeah I really want to use this on Linux too

**Comment by gnocera** [comment]
Hello.
I would like to know if we have some update about this important step for socioboard evolution? Means, if there is already a smooth and fully functional installation for Linux?

We where testing in the past with multiple troubles.

Thank you and Best Regards,

Giuseppe N.

**Comment by BloodyIron** [comment]
Yeah can we get this please?

**Comment by kf202020** [comment]
so basically we cannot install this on linux ?

**Comment by gnocera** [comment]
We were testing on Linux about 1 year ago. We had good results to set up the dashboard. The registration process had some basic issues and the functionality itself (spread messages) was not fully operational. On the other side we also tried on Windows and it was smooth and easier. At that point we decided to stop until the whole installation on Linux will be 100% working, since my strategy is open source based. Regards.

**Comment by BloodyIron** [comment]
Yeah, Windows is not to be used in our environment. Right now this looks to be the best tool to manage social presence, and I really am chomping at the bit to get this usable on Linux! Alternative tools are cloud/hosted, and that doesn't work for us at all. We need our own control here.

So, what's it gonna take to get this installable on Linux with documented steps?

**Comment by socioboard** [comment]
pull new version

**Comment by BloodyIron** [comment]
> pull new version

Actually saw this earlier today! Looking forward to trying it out! Instructions aren't quite end to end though :S
