### ISSUE TITLE
Cant load website

### ISSUE THREAD

**Issue by abodsakah** [socioboard/Socioboard-4.0#233]
When ever i try to open the website i just get a 404 error even tho i tried with Apache and nginx and then i cant seem to get the laravel app_key becuase everytime i run `php artisan key:generate ` i get `Could not open input file: artisan` even tho i did the update and all that.

**Comment by sureshbabu1995** [comment]
Hi, @abodsakah 

I hope some of the below instructions will fix you to an extend please follow the below steps one 

Goto -> PHP folder
`composer install`

**Comment by abodsakah** [comment]
Still dosn't work, you can see my steps here
https://asciinema.org/a/tFyO846rHuXBJ5TeauyJYQvu3

**Comment by sureshbabu1995** [comment]
Hi .. Check the clone once


Your directory files  - http://url1318.globussoft.in/ls/click?upn=pCZsBLi5VdPF-2B0-2FpXEX-2Fu7JlxiIiQfc72dxdIeC2jOprSgH40PKqZZVQEgJhZ9mXCk8w_U31jt5HgHBh7k3Grc5s4l7SADnTuOVNpASOYFQ6rL64GJZFNRKJb2O-2BxVgXL1TDiiXdXSOjeOA9i3-2FMvJcfwTK1738Lt4ClrqUAzzdIwxiZSksyRAoQ-2FNYe52lIC2-2F1yc9aAK7SKSptt-2Br2JDfz1NqkpgNaO9T-2FQRSGx-2BaepJ6B5ILe-2Frrb6ApTOvBElzl6lMr3om7sAqNh552NVRzyLKEkKm96OE0Yh0GXZsWhRQae4kO-2BlGlUwoAJQoHAwYF3t66VybRcCQB76JbALXeDkhg-3D-3D

Git Directory files -  http://url1318.globussoft.in/ls/click?upn=pCZsBLi5VdPF-2B0-2FpXEX-2Fu7JlxiIiQfc72dxdIeC2jOo24rhvKvLmSZ6mCvV6nI04nGmG_U31jt5HgHBh7k3Grc5s4l7SADnTuOVNpASOYFQ6rL64GJZFNRKJb2O-2BxVgXL1TDiiXdXSOjeOA9i3-2FMvJcfwTK1738Lt4ClrqUAzzdIwxiZSksyRAoQ-2FNYe52lIC2-2F1yZxYPpvSrJQguZhF6sXTn8Z3b0M1FD8vebYF-2FfjrovR90-2BK9fCFwUEvGaq7RZFVbvynTKXV9QbeBXpi59vy3BIFwN-2B1zS-2Bm-2BDD88z71PXt-2BM-2FGwd2v7EhCJkJxCV7zJIvv-2FxRHvBc53bj4domkH5maw-3D-3D

On 18/06/2021 13:28, Abdulrahman Sakah wrote:
>
> Still dosn't work, you can see my steps here
> http://url1318.globussoft.in/ls/click?upn=wVOYq0Yhcm6rutzZVQWOeEAXN6ljGUJ75ZKiTCCw3v-2BEEhqtu4vx-2B-2F5JQjtAyF9MSsR76zNklOXD-2BJhLhq-2F5fA-3D-3D5EYw_U31jt5HgHBh7k3Grc5s4l7SADnTuOVNpASOYFQ6rL64GJZFNRKJb2O-2BxVgXL1TDiiXdXSOjeOA9i3-2FMvJcfwTK1738Lt4ClrqUAzzdIwxiZSksyRAoQ-2FNYe52lIC2-2F1y3oAa6naKbtpxvK8xZMVugmpEmUzk7Qy-2BSrM3m67AUK61n-2FyGjjxmmHtqpVB1uRtFR95G0G2LAb7DbKxVyLW2WoyKQVQPw4Co3HBi6P6EeYwg4VoT95A72puL-2BJf5guo50MdfVvp-2FZa2W7vEwNONE2A-3D-3D
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <http://url1318.globussoft.in/ls/click?upn=wVOYq0Yhcm6rutzZVQWOeAyTR0OGTuOgP7Fm7H6pahhay48TmT0HRmOtYb3kDJlOrZ36JNtLr7cgFborr1OtOtArmnQrQJsdmgAMKUazWkgUmTpcT13iz8rFAlzAxOw-2FnQS4_U31jt5HgHBh7k3Grc5s4l7SADnTuOVNpASOYFQ6rL64GJZFNRKJb2O-2BxVgXL1TDiiXdXSOjeOA9i3-2FMvJcfwTK1738Lt4ClrqUAzzdIwxiZSksyRAoQ-2FNYe52lIC2-2F1ylemsEs7C6NW1hU4mk-2FGhEsJsAItYvytme-2F0qePh4lv9AjnfoAQ4TCSoH2ozqdefJaaFkMxAzUHK2ypIiDIrWnQ7CECUgIYVyRl-2FJ1jup-2FnU4YvHUQhn1-2FICGkYSxghtlU2OGo8IRLpaYLcRVt0L1Mw-3D-3D>, 
> or unsubscribe 
> <http://url1318.globussoft.in/ls/click?upn=wVOYq0Yhcm6rutzZVQWOeJdJAXOe3xeRHvz9i2Gt-2FidGQ8Csp5o5DNksqKyd-2F4nvXg-2FE5h3-2FiE-2F7cNP3KJW9SamDpW3LXvBA6xsnj9yL0M5ay1w55beJS6Auqo9J9tisPP7pQ8nmfXmQdmHLtmn-2FJg-3D-3DMFAw_U31jt5HgHBh7k3Grc5s4l7SADnTuOVNpASOYFQ6rL64GJZFNRKJb2O-2BxVgXL1TDiiXdXSOjeOA9i3-2FMvJcfwTK1738Lt4ClrqUAzzdIwxiZSksyRAoQ-2FNYe52lIC2-2F1yPJumek2u4ezm41qLffEDh2KIU3zf-2F9GFYe441rFCw6P-2BX8d5DH56PFOkIvivNGTxDxMCflBMtrUk357f01-2BdpxsuRfXtMwkly-2FwgVtqpRJUPoIJMFhNQYMsBkaW-2ByehJmf9sojM3JhxrvDQv2jDOXA-3D-3D>.
>

-- 
Thanking You

Best Regards,
Gogula Suresh Babu
Software Developer
*
*Bhilai Office:*          First Floor, CHPL Dream Home Apartment,
                               Near Dena Bank, Apollo Hospital Road, 
Junwani,
                               Bhilai, Dist. - Durg, Chhattisgarh, Pin - 
490020

*Bangalore Office :*2nd Floor, Lakshya Towers, KHB Colony, 5th Block
                              Koramangala, Bangalore, Karnataka, Pin - 
560095

Globussoft Global Helpline : 0788-4083007, 0788-4083008
Globussoft Bangalore Helpline : 080-41660003, +91-8550020304
*

**Comment by abodsakah** [comment]
I created artisan file and pasted the code from github but now when i run it i get 
```PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /var/www/Socioboard-4.0/socioboard-web-php/bootstrap/app.php:14
Stack trace:
#0 /var/www/Socioboard-4.0/socioboard-web-php/artisan(20): require_once()
#1 {main}
  thrown in /var/www/Socioboard-4.0/socioboard-web-php/bootstrap/app.php on line 14```

**Comment by abodsakah** [comment]
I created artisan file and pasted the code from github but now when i run it i get 
```PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /var/www/Socioboard-4.0/socioboard-web-php/bootstrap/app.php:14
Stack trace:
#0 /var/www/Socioboard-4.0/socioboard-web-php/artisan(20): require_once()
#1 {main}
  thrown in /var/www/Socioboard-4.0/socioboard-web-php/bootstrap/app.php on line 14```
