### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by ElMandrillo** [socioboard/Socioboard-4.0#78]
Hello,
I have the building error. when I compile the project (Socioboard 3.0) I have an error and about 2000 warnings about variables declared and not used.
S.O .: Windows 10 64bit
IDE: VS2015 community edition (full install) with DotNetCore.1.0.1-VS2015Tools.Preview2. installed

Severity Code Description Project File Line Suppression State
Error CS1061 'FacebookPasswordChangeUserDetail' does not contain a definition for 'userPrimaryEmail' and no extension method 'userPrimaryEmail' accepting a first argument of type '' FacebookPasswordChangeUserDetail 'could be found (SocioboardDataServices.DNX 4.5 .1.0 C: \ Users \ User \ Desktop \ Socioboard-Core-3.0 \ src \ SocioboardDataServices \ Reports \ FacebookReports \ FacebookPageReports.cs 260 Active

Severity Code Description Project File Line Suppression State
Warning CS1717 Assignment made to same variable; did you mean to assign something else? Socioboard.LinkedIn..NET Framework 4.5.1 C: \ Users \ User \ Desktop \ Socioboard-Core \ src \ Socioboard.LinkedIn \ Authentication \ oAuthLinkedIn.cs 233 Active

Can you help me?

**Comment by obusher** [comment]
Build it on commandline (cmd) and it will work. https://github.com/socioboard/Socioboard-Core-3.0/issues/72#issuecomment-387330214

**Comment by socioboard** [comment]
Pull the new version.
