### ISSUE TITLE
Can't create user

### ISSUE THREAD

**Issue by kro82** [socioboard/Socioboard-4.0#79]
Hello, 
I have a problem with creating a user account
I downloaded the socioboard-core-3.0, and I followed all the steps of installation guide, but when I reach the user account creation steps I got a error message "undifined" as on the attached screenshot

![socioboard_error](https://user-images.githubusercontent.com/41017915/42502891-1d79434c-842f-11e8-8d4a-32020cd72dca.jpg)

**Comment by socioboard** [comment]
Hi kro82,
please check your connection string is it correct.

**Comment by kro82** [comment]
I followed the procedure as indicated on the installation documentation
here is the screen shot
![connection_string](https://user-images.githubusercontent.com/41017915/42883000-3fc3aadc-8a92-11e8-8bbd-e38904465a02.png)

**Comment by socioboard** [comment]
debug the code n check what the exact problem n let us know

**Comment by kro82** [comment]
Here is a debug log
[log-20180722.txt](https://github.com/socioboard/Socioboard-Core-3.0/files/2218853/log-20180722.txt)

**Comment by socioboard** [comment]
Pull the new version..
