### ISSUE TITLE
socioboard web based platform not working

### ISSUE THREAD

**Issue by robertcanare** [socioboard/Socioboard-4.0#81]
Hi Socioboard team

We're unable to add our social profiles on socioboard web based, we keep on getting "invalid access token" when we add our facebook, twitter, instagram and linkedin profiles.

We even tried it using a different socioboard + social media accounts using different web browsers to no avail.

Also on premise hosting of socioboard doesn't allow us to create login any socioboard account.

**Comment by socioboard** [comment]
Hi robertcanare,
sorry for inconvenience ,we are checking the issue and will try to resolve soon .
once update will let you know .

Thanks
SB  Team

**Comment by arvs47** [comment]
# #61

**Comment by robertcanare** [comment]
Hi


Even the web based platform, https://www.socioboard.com/ is not working -
invalid access token


Thanks
