### ISSUE TITLE
Pinterest and tumblr accounts missing in Web version as well git edition . 

### ISSUE THREAD

**Issue by arvs47** [socioboard/Socioboard-4.0#82]
Hi socioboard team / Sumit 
I need some clarifications and some tutorials needed .

 Things i  noticed is pinterest account section is missing from the dashboards in both web version in git but their codes and files are present in the source code , so did you guys dropped them or hid them for   any reason  

As of now i can  see only seven accounts here 

 facebook ,twitter , instagram , youtube ,,. google analytic and linkedin  google plus 

so where are  these two , tumblr pinterest  and wordpress in was in initial version , ??? 

can i able to  add somehow , because i found the pinterest codes are present 

And some other doubts i need to  clear from your end ,, 

1 how can i host it in a linux servers like  lamp , lemp machines .. 

2 Any updates for facebook because facebook new updates and policy breaks some features and scopes so how it will reflect in site as of now i cannot login through facebook it shows access token invalid it doesnt generates the token , 

looking for some updates about the new scopes for facebook app submissions

3 How i can use it as a super admin , when i changed user to superadmin in database nothing changed , so do i need to change any other strings ,,

looking for some helpful solutions from you .
i posted in your groups but i didn't got any replay from there so i though this is best ..

Any way its a good application . compared to hootsuite and others you have so many features , but i notice there is some lack of promotions and support , or you were busy in terms of other projects , i know you guys are doing this as house project , but i appreciate for the open source codes ,, 

NB i am not a developer but learning new things **.**

**Comment by obusher** [comment]
https://github.com/socioboard/Socioboard-Core-3.0/issues/75
https://github.com/socioboard/Socioboard-Core-3.0/issues/77

**Comment by arvs47** [comment]
there is no solutions at all .
