### ISSUE TITLE
can't create user error

### ISSUE THREAD

**Issue by demetch** [socioboard/Socioboard-4.0#83]
please after installation i getting this error: can't create user 
help me.
is there default admin user ?

regards

**Comment by arvs47** [comment]
check your mysql connection - in visual studio  check the database is open  in visual studio server explorer-  and provide  mongodb database name .

**Comment by demetch** [comment]
Thanks for reply, it worked now.

please what is default admin user/password ?
how to create or import admin user ?

many thanks dear

**Comment by arvs47** [comment]
i am also looking for it , some old issue thread suggests changing member into superAdmin will change , but i have done and nothing worked , ; looking for some solutions , like facebook logins not working , showing error as token is invalid and pinterest  is missng from the dashboard but the code is present in project ,

**Comment by demetch** [comment]
Ok,thanks.i'm still checking

**Comment by arvs47** [comment]
For admin Access change user type in user table to SuperAdmin 
Signin with gmail or facebook doesn't work - use email

**Comment by obusher** [comment]
https://github.com/socioboard/Socioboard-Core-3.0/issues/77
