### ISSUE TITLE
Update facebook token scopes with latest facebook app features 

### ISSUE THREAD

**Issue by arvs47** [socioboard/Socioboard-4.0#84]
Not able to login in facebook because of facebook the token generated failed or due to some missing scopes or deprecated scopes makes the tokens invalid , or it failed to login , so it is happening both in git hub version and web version , please update it with new scopes for the tokens like publish to groups - and deprecation of publish action makes the token generation failed '

**Comment by obusher** [comment]
https://github.com/socioboard/Socioboard-Core-3.0/issues/75

**Comment by arvs47** [comment]
Do you have a solution , facebook login with https is not enabled in my app settings so i my other applications works fine ,

**Comment by arvs47** [comment]
solved login problem by removing  bio field from the fBuser.cs 

still some problems with the latest scopes , after facebook recent platform changes too many permissions removed , like publish_action , which help to publish post via api behalf of user , so socioboard needs some update based on this new scopes and features

**Comment by socioboard** [comment]
Yes our team updating the socioboard api for with respective new scopes, will push the updated code soon.
Thanks :)

**Comment by demetch** [comment]
@arvs47 @socioboard  help me solved this issue:
Invalid Scopes: user_friends, user_status, publish_actions, user_posts, manage_pages. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

**Comment by arvs47** [comment]
> @arvs47 @socioboard help me solved this issue:
> Invalid Scopes: user_friends, user_status, publish_actions, user_posts, manage_pages. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

remove this publish_actions

**Comment by socioboard** [comment]
Pull the new version.
