### ISSUE TITLE
"Undefined" error when registering user

### ISSUE THREAD

**Issue by apinter** [socioboard/Socioboard-4.0#85]
Trying to deploy Socioboard 3.0.52 on a Win7 following the instructions in the project. VS returns quite a lot of errors, but we got it running, but once try to register a user we get the "Undefined" error message.   
   
Output of Chrome error console:
```jquery-2.1.1.min.js:4 POST http://localhost:6361/api/user/Register 400 (Bad Request)
send @ jquery-2.1.1.min.js:4
ajax @ jquery-2.1.1.min.js:4
myFunction @ (index):909
onsubmit @ (index):538
(index):1 Failed to load http://localhost:6361/api/user/Register: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost:44317' is therefore not allowed access. The response had HTTP status code 400. 
```
Any thoughts on this? This looks like a problem even if we try and sign up on socioboard.com and give the same 400 error.

**Comment by hrdkgtm** [comment]
Update on this as i'm having the same issue, 
I changed the startup.cs at Api.Socioboard to allow sources from https://localhost:44317

previously the error notification was "undefined", now the errot notification becomes "Can't create user"
I tried running the database separately from localhost AND in localhost, yet still getting the same error.

Output from Chrome error console: 
``jquery-2.1.1.min.js:4 POST http://localhost:6361/api/user/Register 400 (Bad Request)
send @ jquery-2.1.1.min.js:4
ajax @ jquery-2.1.1.min.js:4
myFunction @ (index):909
onsubmit @ (index):538 ``

We are running the code using VS2017

**Comment by socioboard** [comment]
Hi apinter and hrdkgtm
I think you have issue with local database, 
Can you please setup local database and check
For creating local database you need to do following steps:
1. Check the mapping files presented in Domain.Socioboard > compiler > resources > mappings
2. For create a local database, requesting you to check column names and table names presented in mappings
3. Then update the hibernate-configuration (in hibernate.cfg.xml file) according to database you created
4. Thats all, You are done :)

**Comment by apinter** [comment]
@socioboard Thanks, tomorrow will going to look into it again and update this issue.

**Comment by hrdkgtm** [comment]
@socioboard 
I tried to setup the database using MariaDB 10.0.25 (like mentioned in the .sql file) and i dont think there is a problem in the database because i tried giving the root credentials and tried using socioboard user (i made it myself) for the database. and it still doesnt work, giving the "Cant create user" error.

the console in Chrome gives a different error tho : 

> Register:1 Failed to load resource: the server responded with a status of 400 (Bad Request)

Full disclosure we did let VS solution to fix "The type or namespace" in Api.Socioboard. because if we do not do that, the Api wont even start. 

so any clues?

**Comment by socioboard** [comment]
Hi hrdkgtm
Can you please test with database schema attached here

[SocioSchema.zip](https://github.com/socioboard/Socioboard-Core-3.0/files/2305362/SocioSchema.zip)

and use following hibernate configuration
Data Source=localhost;User ID=root;Password=;persist security info=False;initial catalog=databasename;pooling=true;charset=utf8; port=3306

**Comment by demetch** [comment]
@apinter 
try install using VS 2015

Regards

**Comment by arslancb** [comment]
Hi I just checked

DB You provided has NO Rows in GroupProfiles

but in your installation screenshot, there are 4 profiles.

I tracked back and the error was Can't Create User and it's checking for Group Profiles

so most probably sample DB file is corrupt or have insufficient required data, please update and let me know

**Comment by signum6** [comment]
I'm having a similar problem. Trying to setup Socioboard-Core-3.0-master. Getting error "Undefined".

In chrome console error: POST http://localhost:6361/api/user/Register net::ERR_CONNECTION_REFUSED

In my hibernate file database settings are: Data Source=localhost;User ID=socioboard;Password=MyPassword;persist security info=False;initial catalog=socioboardlive;pooling=true;charset=utf8; port=3306;

My setup is on a AWS running a windows 2016 server. I'm using VS2015. 

I'm I using the wrong credentials in my hibernate file? Any help would awesome thanks in advance.
