### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by demetch** [socioboard/Socioboard-4.0#86]
hello, 
i get this error when trying to loging:  It seems like your connectivity to the internet is impaired

please help me

**Comment by socioboard** [comment]
Please check the following comment link, you will get the solution

https://github.com/socioboard/Socioboard-Core-3.0/issues/85#issuecomment-414282106

**Comment by demetch** [comment]
Hello sir , still getting the same error, please check here:
my url: https://coralmonitoring.com
user: demetch@gmail.com 
pass: 123456987

please check and help me

Regards

**Comment by Basanagoudaglb** [comment]
basically you are getting the issue because it is going to error in ajax call(in Login function). please check the domain name in appsettings.json

**Comment by socioboard** [comment]
Pull the new version
